### ISSUE TITLE
Version 1.3 does not work with multiple pages on my installation

### ISSUE THREAD

**Issue by mpwt** [JustCarmen/webtrees-simple-menu#2]
Hi Carmen, currently I use version 1.2 for two sites. With version 1.3 I have not been able to get more than one singular page to work. When I update my two existing pages, both pages show the same content (of the second page).

I can create another page with version v1.3 in addition to the two pages with v1.2. This new page is displayed correctly.

Is there anything new to note or a trick how I can update to the new version for more than one page?

I use webtrees 2.1.15 with justlight theme, some vesta add-ons, three charts of magicsunday and PHP 8.1. The link to my webtrees page is https://ffp.bauschaffen.de. Thanks in advance.

**Comment by JustCarmen** [comment]
Tested before release and then it worked, I thought. But I can't get it to work again either. I thought it would be easier if it was not necessary to change the constant ROUTE_URL after each upgrade. So I put a variable part in it, but unfortunately that is not the solution.

It's the same problem as https://github.com/JustCarmen/webtrees-fancy-treeview/issues/114. According to Greg, you have to hard code the page type in the ROUTE_URL. And I thought I found a nice solution for this module by making the page type partially variable. So that users with multiple pages don't have to change the code after each upgrade. Unfortunately it doesn't work.

I need to fix this.

**Comment by mpwt** [comment]
Why don't you read the module name from the module settings stored in the database? There per module "_jc_simple_menu_X_" is stored.

**Comment by JustCarmen** [comment]
That is not possible. It has to be a hard coded name. See Greg's answer here: https://github.com/JustCarmen/webtrees-fancy-treeview/issues/114.

**Comment by mpwt** [comment]
Good, then you should revert the commit https://github.com/JustCarmen/webtrees-simple-menu/commit/68b4afa38d24a47823d0ecf49164402b36e7dbfb and add in the description that an adjustment in the file modul.php is necessary, if more than one page should be created.
